"<html>\n",
  "<head>\n",
    "<title>AWS CloudFormation PHP Sample</title>\n",
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n",
  "</head>\n",
  "<body>\n",
    "<h1>Welcome to the AWS CloudFormation PHP Sample</h1>\n",
    "<p/>\n",
    "<?php\n",
      "// Print out the current data and tie\n",
      "print \"The Current Date and Time is: <br/>\";\n",
      "print date(\"g:i A l, F j Y.\");\n",
    "?>\n",
    "<p/>\n",
    "<?php\n",
      "// Setup a handle for CURL\n",
      "$curl_handle=curl_init();\n",
      "curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,2);\n",
      "curl_setopt($curl_handle,CURLOPT_RETURNTRANSFER,1);\n",
      "// Get the hostname of the intance from the instance metadata\n",
      "curl_setopt($curl_handle,CURLOPT_URL,'http://169.254.169.254/latest/meta-data/public-hostname');\n",
      "$hostname = curl_exec($curl_handle);\n",
      "if (empty($hostname))\n",
      "{\n",
        "print \"Sorry, for some reason, we got no hostname back <br />\";\n",
      "}\n",
      "else\n",
      "{\n",
        "print \"Server = \" . $hostname . \"<br />\";\n",
      "}\n",
      "// Get the instance-id of the intance from the instance metadata\n",
      "curl_setopt($curl_handle,CURLOPT_URL,'http://169.254.169.254/latest/meta-data/instance-id');\n",
      "$instanceid = curl_exec($curl_handle);\n",
      "if (empty($instanceid))\n",
      "{\n",
        "print \"Sorry, for some reason, we got no instance id back <br />\";\n",
      "}\n",
      "else\n",
      "{\n",
        "print \"EC2 instance-id = \" . $instanceid . \"<br />\";\n",
      "}\n",
      "$Database   = \"",
{
   "Fn::GetAtt": [
       "MySQLDatabase",
       "Endpoint.Address"
   ]
},
"\";\n",
"      $DBUser     = \"",
{
   "Ref": "DBUser"
},
"\";\n",
"      $DBPassword = \"",
{
   "Ref": "DBPassword"
},
"\";\n",
      "print \"Database = \" . $Database . \"<br />\";\n",
      "$dbconnection = mysql_connect($Database, $DBUser, $DBPassword)\n",
                      "or die(\"Could not connect: \" . mysql_error());\n",
      "print (\"Connected to $Database successfully\");\n",
      "mysql_close($dbconnection);\n",
    "?>\n",
    "<h2>PHP Information</h2>\n",
    "<p/>\n",
    "<?php\n",
      "phpinfo();\n",
    "?>\n",
  "</body>\n",
"</html>\n"
